server.port = 8884
logging.config = classpath:log4j2-spring.xml

spring.application.name=corgiSchedule
spring.dubbo.registry=zookeeper://127.0.0.1:2181
#spring.dubbo.registry=zookeeper://47.111.180.175:2181