server.port = 8884
logging.config = classpath:log4j2-spring.xml

spring.application.name=corgiSchedule
#spring.dubbo.registry=zookeeper://127.0.0.1:2181
spring.dubbo.registry=zookeeper://47.111.180.175:2181

aliyun.accessKeyId=LTAI4Fwu7uCt6ijGW7rLWbqQ
aliyun.AccessKeySecret=Kxl0JLGjrIyeSc94ZZKGiUTUCSZLx3
aliyun.bucketName=corgi-pic
aliyun.sts.endpoint=sts.cn-beijing.aliyuncs.com
aliyun.endpoint=oss-cn-beijing.aliyuncs.com
aliyun.role.arn=acs:ram::1913874992729850:role/corgimanager

spring.redis.host=r-uf6g1k1pog2v2egdgxpd.redis.rds.aliyuncs.com
spring.redis.port=6379
spring.redis.password=Corgi2020

spring.rabbitmq.host=172.19.22.140
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.virtual-host=/test
